### ISSUE TITLE
is hpilo_es_import compatible with ES 2.2?

### ISSUE THREAD

**Issue by elisiano** [seveas/python-hpilo#105]
After having created my own server.py I launch the hpilo_es_import script but it fails complaining about the mapping.

Here's the debug output of the script:
```
[root@elk01 elasticsearch]# ./hpilo_es_import -x 1 -d                                                                                                                                                              
No handlers could be found for logger "elasticsearch"
Creating hpilo index
Traceback (most recent call last):
  File "./hpilo_es_import", line 149, in <module>
    main()
  File "./hpilo_es_import", line 84, in main
    es.indices.put_mapping(index='hpilo', doc_type='hpilo', body={'hpilo': mapping})
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/indices.py", line 291, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [path : last_updated]')
```

Here are the logs on the ES side: 
```
[2016-03-14 21:29:29,423][INFO ][cluster.metadata         ] [elk01-techops] [hpilo] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2016-03-14 21:29:29,551][INFO ][cluster.routing.allocation] [elk01-techops] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[hpilo][0], [hpilo][4], [hpilo][0]] ...]).
[2016-03-14 21:29:29,569][DEBUG][action.admin.indices.mapping.put] [elk01-techops] failed to put mappings on indices [[hpilo]], type [hpilo]
MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : last_updated]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:148)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2016-03-14 21:29:29,569][INFO ][rest.suppressed          ] /hpilo/_mapping/hpilo Params: {index=hpilo, type=hpilo}
MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : last_updated]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:148)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by seveas** [comment]
I'm using ES 1.5 myself and have only tested against 1.x versions, so it may very well not be compatible. If you know ES a bit, it shouldn't be hard to update the schema for 2.x and I'd welcome a patch that detects the ES version and uses the appropriate schema for it. I won't be able to create such a patch myself anytime soon.
