### ISSUE TITLE
Getting "NameError: global name 'firmware' is not defined" during updates

### ISSUE THREAD

**Issue by ewwhite** [seveas/python-hpilo#161]
I've started receiving the following error during remote firmware pushes:

```
# hpilo_cli esx1ilo update_rib_firmware version=latest -l Administrator -p password123
Downloading ilo4 firmware version 2.55 13856951/13856951 bytes (100%)Traceback (most recent call last):
  File "/usr/bin/hpilo_cli", line 334, in <module>
    main()
  File "/usr/bin/hpilo_cli", line 214, in main
    results = [getattr(ilo, method)(**params)]
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 1872, in update_rib_firmware
    self._upload_file(filename, progress)
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 283, in _upload_file
    while boundary in firmware:
NameError: global name 'firmware' is not defined
```

This only seems to affect a subset of systems, but I don't know what's unique about this particular environment. The hosts are EL6 and the RPM package is installed from the repo.

**Comment by seveas** [comment]
Fixed in 4.1
