### ISSUE TITLE
get_one_time_boot not work

### ISSUE THREAD

**Issue by popelaa** [seveas/python-hpilo#273]
Hello, I install the one time boot and then check if it is installed on ilo5 it breaks. 
>>> ilo.get_persistent_boot() 
[('Boot0013', 'CentOS Linux'), ('Boot0014', 'CentOS'), ('Boot0012', 'Embedded SATA Port 1 HDD : VK000240GWTSV '), ('Boot000A', 'Generic USB Boot'), ('Boot000E', 'Embedded LOM 1 Port 1 : HPE Ethernet 10Gb 2-port 568i Adapter (PXE IPv4)'), ('Boot000C', 'Embedded LOM 1 Port 1 : HPE Ethernet 10Gb 2-port 568i Adapter (HTTP(S) IPv4)'), ('Boot000B', 'Slot 2 Port 1 : HPE InfiniBand EDR/Ethernet 100Gb 1-port 840QSFP28 Adapter - HCA (HTTP(S) IPv4)'), ('Boot0011', 'Slot 2 Port 1 : HPE InfiniBand EDR/Ethernet 100Gb 1-port 840QSFP28 Adapter - HCA (PXE IPv4)'), ('Boot0010', 'Slot 2 Port 1 : HPE InfiniBand EDR/Ethernet 100Gb 1-port 840QSFP28 Adapter - HCA (HTTP(S) IPv6)'), ('Boot000D', 'Embedded LOM 1 Port 1 : HPE Ethernet 10Gb 2-port 568i Adapter (HTTP(S) IPv6)'), ('Boot000F', 'Embedded LOM 1 Port 1 : HPE Ethernet 10Gb 2-port 568i Adapter (PXE IPv6)')]
>>> ilo.set_one_time_boot("Boot000E") 
>>> ilo.get_one_time_boot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python-hpilo/hpilo.py", line 1266, in get_one_time_boot
    return self._info_tag('SERVER_INFO', 'GET_ONE_TIME_BOOT', ('ONE_TIME_BOOT', 'GET_ONE_TIME_BOOT'), process=process)
  File "python-hpilo/hpilo.py", line 742, in _info_tag
    return self._process_info_tag(message, returntags or [tagname], process)
  File "python-hpilo/hpilo.py", line 753, in _process_info_tag
    return process(self._element_children_to_dict(message))
  File "python-hpilo/hpilo.py", line 1265, in process
    return data['boot_type'].lower()
AttributeError: 'tuple' object has no attribute 'lower'

[iLO Firmware Version] 2.42 Apr 05 2021
[iLO Date/Time] Tue Jun 21 10:17:14 2022

**Comment by MusicDev33** [comment]
A little late on this, but this problem was just fixed in this PR:
#298
