### ISSUE TITLE
iLoError not clear after 100% download completion from hpilo_cli

### ISSUE THREAD

**Issue by lilocruz** [seveas/python-hpilo#282]
Hello team, I'm getting the following error after executing hpilo_cli [name-of-server] update_rib_firmware version=latest where the description is not that clear.

`Downloading ilo4 firmware version 2.81 13769998/13769998 bytes (100%)Traceback (most recent call last):
  File "/usr/local/bin/hpilo_cli", line 334, in <module>
    main()
  File "/usr/local/bin/hpilo_cli", line 214, in main
    results = [getattr(ilo, method)(**params)]
  File "/usr/local/lib/python3.7/dist-packages/hpilo.py", line 2085, in update_rib_firmware
    return self._request(root, progress)[1]
  File "/usr/local/lib/python3.7/dist-packages/hpilo.py", line 246, in _request
    header, data =  self._communicate(xml, self.protocol, progress=progress)
  File "/usr/local/lib/python3.7/dist-packages/hpilo.py", line 526, in _communicate
    raise IloError(sock.stderr.read().strip())
hpilo.IloError: b''
`

**Comment by lilocruz** [comment]
The IloError exception is not clear it's just the character b''

**Comment by lilocruz** [comment]
Solved: need to upgrade hponcfg to a version greater than 5.3
