### ISSUE TITLE
I am getting sslerror

### ISSUE THREAD

**Issue by karthikrev** [seveas/python-hpilo#63]
Traceback (most recent call last):
  File "/tmp/check.py", line 36, in <module>
    ilo.ison()
  File "/tmp/oo.py", line 31, in ison
    print self.ilo.get_host_power_status()
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 1062, in get_host_power_status
    process=lambda data: data['host_power'])
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 642, in _info_tag
    header, message = self._request(root)
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 201, in _request
    self._detect_protocol()
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 241, in _detect_protocol
    header, data = self._communicate(b('<RIBCL VERSION="2.0"></RIBCL>'), ILO_HTTP)
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 366, in _communicate
    sock = self._get_socket()
  File "/usr/local/lib/python2.7/site-packages/hpilo.py", line 356, in _get_socket
    except socket.sslerror:
AttributeError: 'module' object has no attribute 'sslerror'

-bash-4.1$ python --version
Python 2.7.9

**Comment by karthikrev** [comment]
I have fixed it by recompiling python by following this 
http://www.webtop.com.au/blog/compiling-python-with-ssl-support-fedora-10-2009020237
Thanks and sorry :-)
