### ISSUE TITLE
Issue changing server name on ilo4 (Gen9) servers

### ISSUE THREAD

**Issue by blackduckx** [seveas/python-hpilo#74]
Hi,

With the latest git, I can not change the server_name of a Gen9 server with ilo4. Right now I did not find any good reason for this behaviour as the XML looks good according to the specs. But the server keep to return Syntax Error

Full trace 
```
......

Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: close
Date: Wed, 18 Mar 2015 04:52:02 GMT
Server: HP-iLO-Server/1.30

<?xml version="1.0"?>
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x0001"
    MESSAGE='Syntax error'
     />
</RIBCL>

Traceback (most recent call last):
  File "/usr/bin/hpilo_cli", line 312, in <module>
    main()
  File "/usr/bin/hpilo_cli", line 199, in main
    results = [getattr(ilo, method)(**params)]
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 1644, in set_server_name
    return self._control_tag('SERVER_INFO', 'SERVER_NAME', attrib={"value": name})
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 670, in _control_tag
    header, message = self._request(root)
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 216, in _request
    message = self._parse_message(data)
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 530, in _parse_message
    raise IloError(message, status)

```

**Comment by seveas** [comment]
Try python-hpilo version 2.11 - this is an iLO firmware bug that 2.11 works around.

**Comment by blackduckx** [comment]
Hello,

Upgrading to the latest firmware may have solve the issue.
I do not have any trouble setting the server_name.
You can safely close this case.

Regards,
Frédéric
