### ISSUE TITLE
Unable to parse xml in get_server_event_log

### ISSUE THREAD

**Issue by tomdymond** [seveas/python-hpilo#84]
Hi, 

On some servers I get errors trying to access the IML log. Using firmware 2.10. 

./hpilo_cli ilo.USE325716P get_server_event_log

Traceback (most recent call last):
  File "./hpilo_cli", line 325, in <module>
    main()
  File "./hpilo_cli", line 212, in main
    results = [getattr(ilo, method)(**params)]
  File "/home/tdymond/python-hpilo/hpilo.py", line 1189, in get_server_event_log
    return self._info_tag('SERVER_INFO', 'GET_EVENT_LOG', 'EVENT_LOG', process=process)
  File "/home/tdymond/python-hpilo/hpilo.py", line 663, in _info_tag
    header, message = self._request(root)
  File "/home/tdymond/python-hpilo/hpilo.py", line 228, in _request
    message = self._parse_message(data[:pos])
  File "/home/tdymond/python-hpilo/hpilo.py", line 521, in _parse_message
    message = etree.fromstring(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1024, column 37

Using: 

commit a261077bde1c7c8f88ad855e0683aaf2c1370bfc

**Comment by seveas** [comment]
That's not very nice... Unfortunately that does look like a bug in the iLO firmware. Could you try the latest version? If it still happens, please save a complete respone with the following command:

`./hpilo_cli --save-response=for_dennis.txt ilo.USE325716P get_server_event_log`

And mail this file to dennis@kaarsemaker.net. Should you wish to redact information from this XML file, please do so with a text editor that does not mess with line endings, and make sure you only overwrite individual bytes with X'es. A hexeditor would probably be best.
