### ISSUE TITLE
Ilo2 - hpilo.get_persistent_boot triggers AttributeError

### ISSUE THREAD

**Issue by Eagllus** [seveas/python-hpilo#93]
get_persistent_boot() on a Ilo2 returns AttributeError

```
>>> hpilo.get_persistent_boot()
Traceback (most recent call last):
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/hpilo.py", line 1188, in get_persistent_boot
    return self._info_tag('SERVER_INFO', 'GET_PERSISTENT_BOOT', ('PERSISTENT_BOOT', 'GET_PERSISTENT_BOOT'), process=process)
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/hpilo.py", line 699, in _info_tag
    return self._process_info_tag(message, returntags or [tagname], process)
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/hpilo.py", line 712, in _process_info_tag
    return process(self._element_to_dict(message))
  File "/Users/ronald/.virtualenvs/lux/lib/python3.5/site-packages/hpilo.py", line 1183, in process
    data.sort(key=lambda x: x[1])
AttributeError: 'dict_items' object has no attribute 'sort'
```
not sure if this is a bug in the ilo 2 or in the library.

**Comment by seveas** [comment]
This is a bug the library when used with python 3. There are two workarounds you can use until I fix it: use python 2 or change line 1182 to `data = list(data.items())`.

**Comment by Eagllus** [comment]
Created a pull request for this problem #94
Tell me what you think or that you have a cleaner way of fixing the code.

**Comment by seveas** [comment]
Heh, I had already committed (but not pushed) an alternative. No need for the PY3 guard, it works in python2 as well.

**Comment by Eagllus** [comment]
Thanks, dint know if that would work in python2
