### ISSUE TITLE
Unable to set snmp_address_1_trapcommunity via CLI or puppet module

### ISSUE THREAD

**Issue by woneill** [seveas/python-hpilo#98]
I can't figure out the correct syntax to set snmp_address_1_trapcommunity either via the hpilo_cli utility or puppet modules. I think it has to do with it expecting a dict but somewhere it's getting converted incorrectly.

This puppet code:
```puppet
  ilo_settings {
    'snmp':
      settings => {
        'snmp_address_1_trapcommunity' => {
          'version'  => '1',
          'value'    => 'foo',
        }
      }
    };
  }
```
ends up erroring out 
```
Notice: /Stage[main]/Hp::Ilo::Config/Ilo_settings[snmp]/settings: settings changed {'snmp_address_1_trapcommunity' => 'foo'} to 'snmp_address_1_trapcommunityversion1valuefoo'
Debug: Executing '/usr/bin/hpilo_cli -Plocal --json localhost mod_snmp_im_settings snmp_address_1_trapcommunity=version1valuefoo'
Error: /Stage[main]/Hp::Ilo::Config/Ilo_settings[snmp]: Could not evaluate: Execution of '/usr/bin/hpilo_cli -Plocal --json localhost mod_snmp_im_settings snmp_address_1_trapcommunity=version1valuefoo' returned 1: Traceback (most recent call last):
  File "/usr/bin/hpilo_cli", line 321, in <module>
    main()
  File "/usr/bin/hpilo_cli", line 200, in main
    results = [getattr(ilo, method)(**params)]
  File "/usr/lib/python2.6/site-packages/hpilo.py", line 1472, in mod_snmp_im_settings
    for key_ in val.keys():
AttributeError: 'str' object has no attribute 'keys'
```

I've also tried setting it directly using the dotted notation with no luck:
```
# /usr/bin/hpilo_cli -Plocal --json localhost mod_snmp_im_settings snmp_address_1_trapcommunity.value='foo' snmp_address_1_trapcommunity.version='1'
Ilo.mod_snmp_im_settings [snmp_access=None] [web_agent_ip_address=None]
[snmp_address_1=None] [snmp_address_1_rocommunity=None]
[snmp_address_1_trapcommunity=None] [snmp_address_2=None]
[snmp_address_2_rocommunity=None] [snmp_address_2_trapcommunity=None]
[snmp_address_3=None] [snmp_address_3_rocommunity=None]
[snmp_address_3_trapcommunity=None] [snmp_port=None] [snmp_trap_port=None]
[snmp_v3_engine_id=None] [snmp_passthrough_status=None]
[trap_source_identifier=None] [os_traps=None] [rib_traps=None]
[cold_start_trap_broadcast=None] [snmp_v1_traps=None] [cim_security_mask=None]
[snmp_sys_location=None] [snmp_sys_contact=None]
[agentless_management_enable=None] [snmp_system_role=None]
[snmp_system_role_detail=None] [snmp_user_profile_1=None]
[snmp_user_profile_2=None] [snmp_user_profile_3=None]:
Configure the SNMP and Insight Manager integration settings. The trapcommunity
settings must be dicts with keys value (the name of the community) and version
(1 or 2c)
```

**Comment by seveas** [comment]
Ok, that's a *really* daft bug in hpilo.py...

See if you can spot the difference:

```
--- a/hpilo.py
+++ b/hpilo.py
@@ -1482,7 +1482,7 @@ class Ilo(object):
                     etree.SubElement(elt, key.upper(), VALUE=str(val))
                 elements.append(elt)
         return self._control_tag('RIB_INFO', 'MOD_SNMP_IM_SETTINGS', elements=elements)
-    mod_snmp_im_settings.requires_dict = ['snmp_user_profile_1', 'snmp_user_profile_2', 'snmp_user_profile_3'
+    mod_snmp_im_settings.requires_dict = ['snmp_user_profile_1', 'snmp_user_profile_2', 'snmp_user_profile_3',
             'snmp_address_1_trapcommunity', 'snmp_address_2_trapcommunity', 'snmp_address_3_trapcommunity']
 
     def mod_sso_settings(self, trust_mode=None, user_remote_cons_priv=None,
```

Will patch and release

**Comment by woneill** [comment]
Wow- I looked at that line for a long time and had a hard time picking it out. Thanks!
